### ISSUE TITLE
No county selection available

### ISSUE THREAD

**Issue by PlumbumDN** [smartcuc/COVID-19#16]
I just switched from app.js to appNew.js, but came across the problem, that the county selector is empty.
Tried to figure out why, but I think everything is configured correctly.
Any suggestions?
![2020-04-06 15_07_29-Window](https://user-images.githubusercontent.com/6172126/78561687-75418d80-7818-11ea-87f4-b741b3db5447.png)

**Comment by Verbalinsurection** [comment]
Hello,

Do you have update your dashboard json with the last one available on the repo ?

**Comment by smartcuc** [comment]
![grafik](https://user-images.githubusercontent.com/21308626/78589651-d54c2a00-7840-11ea-815e-c37e50187bb0.png)

**Comment by smartcuc** [comment]
Yes, dashboard json are up to date.

**Comment by Verbalinsurection** [comment]
> Yes, dashboard json are up to date.
> 

Hello, I say this for PlumbumDN

**Comment by PlumbumDN** [comment]
Hello, yes its the version from the repo. 
![2020-04-07 07_26_29-COVID-19 per Country - Grafana](https://user-images.githubusercontent.com/6172126/78633198-3f94b700-78a1-11ea-93e2-59cd12a2bb44.png)

**Comment by PlumbumDN** [comment]
app.js and appNew.js also show no errors, so I´m a bit confused

**Comment by Verbalinsurection** [comment]
On your influxdb, make a request :
`SHOW TAG VALUES ON "covid19" WITH KEY = "country"`

> (replace covid19 with the name of your database)

And check if country is listed

**Comment by PlumbumDN** [comment]
`> SHOW TAG VALUES ON "covid19" WITH KEY = "country"
name: Corona
key     value
---     -----
country Afghanistan
country Albania
country Algeria
country Andorra
country Angola
country Antigua and Barbuda
country Argentina
country Armenia
country Australia
country Austria
country Azerbaijan
country Bahamas
country Bahrain
country Bangladesh
country Barbados
country Belarus
country Belgium
country Belize
country Benin
country Bhutan
country Bolivia
country Bosnia and Herzegovina
country Botswana
country Brazil
country Brunei
country Bulgaria
country Burkina Faso
country Burma
country Burundi
country Cabo Verde
country Cambodia
country Cameroon
country Canada
country Central African Republic
country Chad
country Chile
country China
country Colombia
country Congo (Brazzaville)
...
`

**Comment by PlumbumDN** [comment]
Fixed the issue by changing variable request to SHOW TAG VALUES ON "covid19" WITH KEY = "country"
The covid19 measurement seems to be not found otherwise
