### ISSUE TITLE
tag values for country is empty in InfluxDB

### ISSUE THREAD

**Issue by rakanbakir** [smartcuc/COVID-19#17]
<img width="444" alt="Screen Shot 2020-04-10 at 2 17 37 PM" src="https://user-images.githubusercontent.com/43639030/78987252-2f493a00-7b36-11ea-9ba8-4674d805902c.png">

**Comment by Verbalinsurection** [comment]
Hello, more info to provide ? like how you sue the app, other data missing or just the tag ?
