### ISSUE TITLE
node issue 

### ISSUE THREAD

**Issue by karlzre** [smartcuc/COVID-19#21]
Hi, 

I have that issue, can you help me to fix it ?

> 2020-04-13 13:18:28 - Running update
(node:2063) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at getCountryData (/home/pi/COVID-19/appNew.js:184:37)
    at Covid (/home/pi/COVID-19/appNew.js:241:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2063) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2063) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Verbalinsurection** [comment]
Hello,
This is like the previous anomaly with countries name change. Do you use the latest version of code or docker image ?
Tha actual code works OK .

**Comment by karlzre** [comment]
i just updated from git and looks ok now.
Thx

**Comment by Verbalinsurection** [comment]
Good :)
Issue can be closed

**Comment by ftx** [comment]
Same issue with latest code :(

**Comment by Verbalinsurection** [comment]
New country in source file : Micronesia
I add the information in code with https://github.com/smartcuc/COVID-19/pull/33
Docker image is up to date
