### ISSUE TITLE
No Recovered field

### ISSUE THREAD

**Issue by karlzre** [smartcuc/COVID-19#5]
Hi, 

I see that ther eis no recovere field in my data base.
Is this not sync in the app ?

SHOW FIELD KEYS ON covid19
name: Corona
fieldKey  fieldType
--------  ---------
Confirmed float
Deaths    float

**Comment by DoM1niC** [comment]
Yes here the same

**Comment by rbfussell** [comment]
Comment on last commit was "changed to new CSV and removed recovered stat"   Currently no recovery data is being published by the source being used.  Didn't look into why,  they shifted to only deaths and confirmed for  the new csv format.

**Comment by smartcuc** [comment]
Right, the source of the file has stoppt to provide the firgures for recovered.

**Comment by karlzre** [comment]
maybe changing to another api ?
i find this one but i'm not able t implement it .
They said they update every 15 min.
https://api-sports.io/documentation/covid-19#section/Introduction

**Comment by kirbah** [comment]
The data is back again https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by smartcuc** [comment]
Will release a new version with another source that is more stable.

**Comment by nrosier** [comment]
The data seems to be back; any chance on fixing the old app to include this? I tried to re-add the recovered code but it strangely enough gave errors and I'm not a javascript expert :-(

**Comment by smartcuc** [comment]
Your map will work with the 3 letter iso code.

**Comment by smartcuc** [comment]
![grafik](https://user-images.githubusercontent.com/21308626/77953419-8bf25c80-72cd-11ea-84b9-574080f0ca00.png)

![grafik](https://user-images.githubusercontent.com/21308626/77953487-aa585800-72cd-11ea-9a80-9e02d3259406.png)

![grafik](https://user-images.githubusercontent.com/21308626/77953525-be03be80-72cd-11ea-9624-0908c48b9e41.png)

**Comment by nrosier** [comment]
Thanks, that fixed it :-)
Thanks for the tool, great work!!!!!!!

**Comment by karlzre** [comment]
It it better to use the new script ?
How often is it updated ?

**Comment by smartcuc** [comment]
Well, I would recomment to use the appNew.js. The app and ccp.json will updated as needed. The data scource gets updated once a day.

**Comment by karlzre** [comment]
Hi,

I proposed your dashboard to my boss @ the Belgian civile protection to
show it on a waalbord ;-)

here in belgium data are updated around 11 AM - 12.
It looks like the data are updated during the night , so i alwais have the
data of teh day before.
Do you think it should be possible to update data more often ?

**Comment by smartcuc** [comment]
Well, I have to rely on the source of the information and they doing the update only once a day. If you have a source for the Belgium information, I can take a look into them...

**Comment by karlzre** [comment]
this one looks to be the "official"  and look to have JSON API
https://fair.healthdata.be/dataset/9c20457b-e66d-4377-ab8e-d48f6dc2b034

**Comment by smartcuc** [comment]
Have taken a look to all file, but  they do not update more than one time per day and some iformaion are not usefull (e.g. deaths =<5). Any other source?
> 
> this one looks to be the "official" and look to have JSON API https://fair.healthdata.be/dataset/9c20457b-e66d-4377-ab8e-d48f6dc2b034
> […](#)
