### ISSUE TITLE
Fails with some dns error even though dns is working fine

### ISSUE THREAD

**Issue by hagabla** [smartcuc/COVID-19#7]
The error message i get is the following:

`(node:8489) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND xxxx xxxx:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
(node:8489) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8489) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

dns on the host works fine, i can wget the url, i can lookup the hostname.

seems to be an IPv6 issue, if i limit it to IPv4 it seems to work

in getCovidData {} i added
```
 var https = require('https');
 var agent = new https.Agent({ family: 4 });
return axios.get(url, { httpsAgent: agent });
```

(i have zero experience with node, so that may be the worst solution ever)

**Comment by smartcuc** [comment]
Well, as long as it is working fine for you, its okay. However, when you don't use a proxy, you could alos comment out line 48, like:
// const axios = require ('axios').create(axiosDefaultConfig);
